### ISSUE TITLE
daemon onix y onix-qt no arrancan en modo testnet

### ISSUE THREAD

**Issue by NiCkEl5** [onix-project/onixcoin#13]
Compilando onixd y onix-qt en la rama tesnet estos no inician dejando el siguiente error:

```
~/onixcoin$ ./ONIX-qt 
ONIX-qt: src/main.cpp:2814: bool InitBlockIndex(): Assertion `hash == hashGenesisBlock' failed.
Aborted (core dumped)
```

**Comment by hbastidas** [comment]
hola saludos, gracias por permitirte unos minutos y probar

este issue corresponde a la rama testnet y lo he modificado para resolverlo, el ultimo commit es
https://github.com/onix-project/onixcoin/commit/68539c0c280c64b001cb3e3b1f40d2d30d74f417

plz compila y una vez tengas el deamon listo ejecuta con estos flags

./ONIX-qt -testnet -addnode=107.170.213.97
o 
./ONIXd -testnet -addnode=107.170.213.97
