### ISSUE TITLE
No se puede desencriptar wallet

### ISSUE THREAD

**Issue by NiCkEl5** [onix-project/onixcoin#18]
![onixencrypterror](https://user-images.githubusercontent.com/6575044/51541700-c0f95880-1e59-11e9-964a-9785f21e6eb4.jpg)

Encripte mi billetera pero no puedo desencriptarla si voy al menu no veo opcion para hacerlo como tampoco haciendo doble click en el candado de la UI

**Comment by CarmeloCampos** [comment]
Puedes hacerlo desde la consola

**Comment by hbastidas** [comment]
> Puedes hacerlo desde la consola

plz @CarmeloCampos explica como hacerlo para que quede en la base de conocimiento.

**Comment by CarmeloCampos** [comment]
> ![onixencrypterror](https://user-images.githubusercontent.com/6575044/51541700-c0f95880-1e59-11e9-964a-9785f21e6eb4.jpg)
> 
> Encripte mi billetera pero no puedo desencriptarla si voy al menu no veo opcion para hacerlo como tampoco haciendo doble click en el candado de la UI

@NiCkEl5 Vas a help (ayuda)
Y después donde dice "Ventana de depuración" o en ingles sería "Debug window"
![image](https://user-images.githubusercontent.com/31357533/55495256-1a23fc00-5602-11e9-8bfd-5086da4216f5.png)

Despues, se dirije a consola, y escribe `walletpassphrase contraseña tiempo
![image](https://user-images.githubusercontent.com/31357533/55496300-548e9880-5604-11e9-91cf-d4a09c6f4b8a.png)

ejemplo: 
![image](https://user-images.githubusercontent.com/31357533/55496364-7be56580-5604-11e9-956a-0ddb79c2d2b6.png)

Listo @hbastidas

**Comment by hbastidas** [comment]
@CarmeloCampos tremendo!
